### ISSUE TITLE
MultiDex bug in some devices

### ISSUE THREAD

**Issue by quim-motger** [BlunchDev/blunch_android#119]
When launching the app in some devices, a MultiDex error is shown, althought it was apparently solved by adding changes in gradle file related with this configuration. Apparently some methods need to be override when first launching the app.

**Comment by victorpm5** [comment]
travis problem with multidex installation:

dev.blunch.blunch.ExampleUnitTest > addition_isCorrect FAILED
    java.lang.RuntimeException: java.lang.RuntimeException: Multi dex installation failed (/home/travis/build/BlunchDev/blunch_android/app/. (Is a directory)).
        Caused by:
        java.lang.RuntimeException: Multi dex installation failed (/home/travis/build/BlunchDev/blunch_android/app/. (Is a directory)).
dev.blunch.blunch.adapters.MenuListAdapterTest > getCountTest STARTED
dev.blunch.blunch.adapters.MenuListAdapterTest > getCountTest FAILED
    java.lang.RuntimeException: java.lang.RuntimeException: Multi dex installation failed (/home/travis/build/BlunchDev/blunch_android/app/. (Is a directory)).
        Caused by:
        java.lang.RuntimeException: Multi dex installation failed (/home/travis/build/BlunchDev/blunch_android/app/. (Is a directory)).

**Comment by quim-motger** [comment]
Solved
