### ISSUE TITLE
Bug in consulting methods

### ISSUE THREAD

**Issue by quim-motger** [BlunchDev/blunch_android#17]
Issue related with issue #16 

Getter methods for information that has been retrieved from Firebase are not always working properly. This may have something to do with the fact that not all data from Firebase has been retrieved when we try to access the repositories and get information (such as Dish information).

**Comment by casassg** [comment]
Individual changes of listener implementations should be considered. Let's make a branch and solve it one by one

**Comment by quim-motger** [comment]
I think we are looking at this at the wrong way. I've just taken a look at this, but as our problem is how to properly translate a typical SQL query for Firebase, I think first points in this article should do the trick. Maybe listeners is not a good option.

After tomorrow's meeting I would like to try to solve it myself. We'll discuss it.

**Comment by quim-motger** [comment]
https://www.firebase.com/blog/2013-10-01-queries-part-one.html

Forgot to add link
