### ISSUE TITLE
Only time but not date can be set to menus

### ISSUE THREAD

**Issue by quim-motger** [BlunchDev/blunch_android#24]
We are only considering the hour (time) but not de day/month/year of the menus, it can not be set in creation time and it is not retrieved neither when getting information

**Comment by quim-motger** [comment]
Assigned to @pberge too

**Comment by AlbertSuarez** [comment]
It works but it's necessary to fix some things.

**Comment by quim-motger** [comment]
@AlbertSuarez @pberge remember please to notify me by closing this issue when it is solved.

**Comment by AlbertSuarez** [comment]
Solved! A pull requested was opened. #35
