### ISSUE TITLE
Menus don't have a "caducity date"

### ISSUE THREAD

**Issue by quim-motger** [BlunchDev/blunch_android#25]
Menus have "start time" and "end time", which also should include date itself , and the end time should be used to remove Menus that have already passed.

The idea is these menus should prevail on the system for future features, but currently there is no way to filter them as there is no date for them.

Bug #24 needs to be solved in order to solve this.

**Comment by AlbertSuarez** [comment]
I consider a caducated menu when its final date is greater than actual date.

**Comment by quim-motger** [comment]
Yes, this has already been solved.

Menus satisfying the condition you mentioned are not shown in the lists of menus, although they are not deleted from the system neither. 

This will be added to master once it has been fully tested (probablt by tomorrow)

**Comment by quim-motger** [comment]
Closed
