### ISSUE TITLE
Big inconsistence style between different activities

### ISSUE THREAD

**Issue by quim-motger** [BlunchDev/blunch_android#28]
There are some activities like:

- NewCollaborativeMenuActivity
- NewPaymentMenuActivity

which have a style way different than the others (and also a bit "rudimentary"). Main idea is fine but it nits enhancement.

Also, EditTexts have a hint which is placed as an initial text. It is annoying for the user to delete this text and then write over it, and also there are some strange checks related with this initial text. 

There is a method EditText.setHint(String hint) that allows to set an initial Hint for a EditText, such as "Place text here...", which is not real text (it is not retrieved when calling EditText.getText()) and it only appears if the field is empty.

**Comment by AlbertSuarez** [comment]
It has improved a lot the interface of NewCollaborativeMenu and NewPaymentMenu activities.

**Comment by quim-motger** [comment]
Interface crushes.

Dishes in PaymentMenu and CollaborativeMenu are not shown in both Get activities. Branch Historia4 cannot be merged.

**Comment by AlbertSuarez** [comment]
No worries, I will solve it!

**Comment by quim-motger** [comment]
Not a repository/service problem, as it has been tested and dishes are retrieved properly. I can give support for fixing this today.

**Comment by casassg** [comment]
What's the status of the interfaces?

**Comment by quim-motger** [comment]
Missing:

- New Collaborative Menu Answer Activity

Will be done by the end of the day, ready for the demo.
