### ISSUE TITLE
Bad top bar colouring

### ISSUE THREAD

**Issue by casassg** [BlunchDev/blunch_android#69]
In valoracion and menu colaboratiu response the status bar is painted in an incorrect colour. @pberge @AlbertSuarez do you know why?

**Comment by AlbertSuarez** [comment]
Not yet, we'll investigated it!

**Comment by quim-motger** [comment]
What is this? @casassg are you aware of it?

**Comment by casassg** [comment]
I'm aware, trying to solve it. Not sure what caused it yet

**Comment by casassg** [comment]
@quim-motger @AlbertSuarez @pberge did you know any other activity where this happened?

**Comment by quim-motger** [comment]
The problem is I've never seen this happening, so I'm not sure what this is referring to.
