### ISSUE TITLE
Collaborative proposals and payment menu petitions can be seen by all users, they should be visible only to the owner

### ISSUE THREAD

**Issue by victorpm5** [BlunchDev/blunch_android#72]

**Comment by quim-motger** [comment]
Correct behaviour must be, whenever a user enters to the detail info view of a menu:

- If I'm not enrolled in any way with the menu, I shouldn't be able to see nothing but the menu detail info
- If I'm participating in the menu, I should be able to enter to the chat
- If I'm the owner of the menu, I should be able to both enter the chat and see all participations
